from functions1_1 import convertor
from functions1_2 import convertor
from functions1_3 import solve
from functions1_4 import filter
from functions1_5 import permuta
from functions1_6 import rever
from functions1_7 import has_33
from functions1_8 import spy_game
from functions1_9 import sphere_volume
from functions1_10 import uni
from functions1_11 import pol
from functions1_12 import histogram
